// Compass tab: collapsible sections, People moved in from its own tab
const { chromium } = require('playwright'); const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '../../public'), S = process.env.S;
const W = +(process.env.W || 390), H = +(process.env.H || 844), touch = process.env.T !== '0', dark = process.env.D === '1';
const results = []; const ok = (n, c, i) => results.push({ n, pass: !!c, i: c ? undefined : i });
(async () => { const b = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined, channel: process.env.CHROMIUM ? undefined : 'chromium' });
  const ctx = await b.newContext({ viewport: { width: W, height: H }, hasTouch: touch, isMobile: touch, colorScheme: dark ? 'dark' : 'light', deviceScaleFactor: 2 });
  await ctx.route(/^https?:\/\/(fonts\.(googleapis|gstatic)\.com|www\.google\.com|accounts\.google\.com)\//, r => r.abort()); await ctx.route('http://compass.test/**', async route => { const u = new URL(route.request().url()); let p = u.pathname === '/' ? '/index.html' : u.pathname, body, type;
    if (p === '/vendor/firebase.js') { body = fs.readFileSync(path.join(__dirname, 'mockfb.js')); type = 'text/javascript'; } else if (p === '/firebase-config.js') { body = 'window.COMPASS_FIREBASE_CONFIG={apiKey:"t",authDomain:"x",projectId:"x",appId:"x"}'; type = 'text/javascript'; } else { try { body = fs.readFileSync(path.join(root, p)); } catch (e) { return route.fulfill({ status: 404, body: '' }); } type = p.endsWith('.js') ? 'text/javascript' : 'text/html'; }
    route.fulfill({ status: 200, body, contentType: type }); });
  let p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message));
  const tap = async s => { const l = typeof s === 'string' ? p.locator(s).first() : s; await l.scrollIntoViewIfNeeded().catch(()=>{}); touch ? await l.tap() : await l.click(); await p.waitForTimeout(200); };
  const tag = W + (dark ? 'd' : '');
  await p.goto('http://compass.test/'); await p.waitForTimeout(500); await tap('.lhero [data-act=signin]'); await p.waitForTimeout(600);
  await tap('[data-act=obNext]'); await p.fill('#ob-goal', 'Calmer and closer to family'); for (const v of ['rel', 'body', 'mind']) await tap(`[data-act=obValue][data-v=${v}]`);
  while (await p.locator('[data-act=obNext]').count()) await tap('[data-act=obNext]');
  await p.waitForTimeout(500);
  ok('no People tab in the tab bar', await p.locator('[data-act=tab][data-t=people]').count() === 0 && await p.locator('[data-act=tab]').count() === 5);
  await tap('[data-act=tab][data-t=compass]'); await p.evaluate(() => scrollTo(0, 0));
  const secs = await p.locator('.csec').count();
  ok('Compass shows collapsed sections', secs >= 9 && await p.locator('.csec.open').count() === 0 && await p.locator('.csb').count() === 0, secs);
  const h = await p.evaluate(() => document.querySelector('.csecs').getBoundingClientRect().height);
  ok('collapsed list is short (under ~1.2 screens)', h < Math.max(H * 1.3, 860), h);
  ok('summaries say something useful', /Calmer and closer/.test(await p.locator('#csec-goal .cst small').innerText()) && /free hours/.test(await p.locator('#csec-week .cst small').innerText()) && /3 values/.test(await p.locator('#csec-values .cst small').innerText()));
  await p.screenshot({ path: `${S}/cs-closed-${tag}.png` });
  await tap('[data-act=cSec][data-k=people]');
  ok('tap opens People', await p.locator('#csec-people.open #pForm').count() === 1 && await p.locator('[data-act=cSec][data-k=people]').getAttribute('aria-expanded') === 'true');
  await p.fill('#pName', 'Sam'); await tap('#pForm button[type=submit]'); await p.waitForTimeout(300);
  ok('adding a person works inside Compass', /Sam/.test(await p.locator('#csec-people').innerText()) && await p.locator('#csec-people.open').count() === 1);
  ok('People summary counts them', /1 person/.test(await p.locator('#csec-people .cst small').innerText()), await p.locator('#csec-people .cst small').innerText());
  await tap('#csec-people [data-act=called]').catch(() => {});
  await tap('[data-act=cSec][data-k=values]');
  ok('two sections can be open', await p.locator('.csec.open').count() === 2);
  await tap('[data-act=cSec][data-k=values]');
  ok('tap again closes', await p.locator('#csec-values.open').count() === 0);
  await tap('[data-act=cSec][data-k=goal]'); await p.fill('#p-goal', 'Calmer, fitter'); await p.waitForTimeout(900);
  await tap('[data-act=cSec][data-k=app]');
  ok('Settings holds colours, backup and run setup', await p.locator('#csec-app [data-act=export]').count() === 1 && await p.locator('#csec-app [data-act=redoOb]').count() === 1);
  await tap('[data-act=cSec][data-k=cal]');
  ok('Calendar section keeps Plan and Export', await p.locator('#csec-cal [data-act=gotoPlan]').count() === 1 && await p.locator('#csec-cal [data-act=icsOpen]').count() === 1);
  await p.screenshot({ path: `${S}/cs-open-${tag}.png`, fullPage: true });
  const hs = await p.evaluate(() => document.documentElement.scrollWidth > innerWidth); const wide = await p.evaluate(() => [...document.querySelectorAll('#main *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1).slice(0, 5).map(e => e.tagName + '.' + e.className + ' ' + Math.round(e.getBoundingClientRect().right) + ' ' + (e.closest('.csec') || {}).id)); ok('no sideways scroll', !hs, wide);
  await p.reload(); await p.waitForTimeout(1200); await tap('[data-act=tab][data-t=compass]');
  ok('open sections are remembered', await p.locator('#csec-people.open').count() === 1 && await p.locator('#csec-app.open').count() === 1);
  ok('goal edit saved', /Calmer, fitter/.test(await p.locator('#csec-goal .cst small').innerText()));
  await tap('[data-act=tab][data-t=today]'); await tap('[data-act=tab][data-t=week]'); await tap('[data-act=tab][data-t=review]'); await tap('[data-act=tab][data-t=tasks]');
  ok('no page errors', errs.length === 0, errs);
  const f = results.filter(r => !r.pass); console.log(`csec ${tag}: ${results.length - f.length}/${results.length} passed`); f.forEach(x => console.log('  FAIL', x.n, JSON.stringify(x.i || '').slice(0, 300)));
  await b.close(); })().catch(e => { console.log('CRASH', e.message.split('\n')[0]); process.exit(1); });
