// Unit tests for the three-way merge pulled straight out of index.html
const src = require('fs').readFileSync(require('path').join(__dirname, '../../public/index.html'), 'utf8');
const grab = name => { const i = src.indexOf(name); let d = 0, j = src.indexOf('{', i); for (let k = j; k < src.length; k++) { if (src[k] === '{') d++; else if (src[k] === '}') { d--; if (!d) return src.slice(i, k + 1); } } };
const line = re => src.match(re)[0];
eval([line(/const cpU = .*\n/), line(/const stable = .*\n/), line(/const same = .*\n/), 'function isObj(v) { return v && typeof v === "object" && !Array.isArray(v); }', line(/const keyedArr = .*\n/), grab('function merge3(')].join('\n') + '\nglobalThis.merge3 = merge3; globalThis.same = same;');
const R = []; const ok = (n, c, i) => R.push({ n, pass: !!c, i });
const J = JSON.stringify;
let m;
m = merge3({ a: 1 }, { a: 1 }, { a: 2 }); ok('only remote changed → remote', J(m) === J({ a: 2 }), m);
m = merge3({ a: 1 }, { a: 3 }, { a: 1 }); ok('only local changed → local', J(m) === J({ a: 3 }), m);
m = merge3({ a: 1, b: 1 }, { a: 2, b: 1 }, { a: 1, b: 2 }); ok('different keys → both', m.a === 2 && m.b === 2, m);
m = merge3({ a: 1 }, { a: 2 }, { a: 3 }); ok('same scalar clash → this device wins', m.a === 2, m);
m = merge3({ x: { t: true } }, {}, { x: { t: true } }); ok('local deletion of untouched key → deleted', !('x' in m), m);
m = merge3({ x: 1 }, {}, { x: 2 }); ok('deleted here but edited there → keep the edit', m.x === 2, m);
m = merge3({ x: 1 }, { x: 1 }, {}); ok('deleted there, untouched here → deleted', !('x' in m), m);
m = merge3({}, { n: 'a' }, { m: 'b' }); ok('both add different keys', m.n === 'a' && m.m === 'b', m);
m = merge3({ c: { gym: 1 } }, { c: { gym: 2 } }, { c: { gym: 2 } }); ok('counter +1 and +1 → 3', m.c.gym === 3, m);
m = merge3({ c: {} }, { c: { gym: 1 } }, { c: { gym: 1 } }); ok('counter from nothing +1 +1 → 2', m.c.gym === 2, m);
m = merge3({ c: { gym: 2 } }, { c: { gym: 1 } }, { c: { gym: 3 } }); ok('counter −1 here, +1 there → 2', m.c.gym === 2, m);
m = merge3({ c: { gym: 1 } }, { c: { gym: 0 } }, { c: { gym: 0 } }); ok('counter never below zero', m.c.gym === 0, m);
m = merge3({ months: { '2026-10': { c: { x: 0 } } } }, { months: { '2026-10': { c: { x: 1 } } } }, { months: { '2026-10': { c: { x: 1 } } } }); ok('monthly counters add up too', m.months['2026-10'].c.x === 2, m);
m = merge3({ name: 'c' }, { name: 'c2' }, { name: 'c2' }); ok('a field named name is not a counter', m.name === 'c2', m);
const base = [{ id: 'a', n: 'A' }, { id: 'b', n: 'B' }];
m = merge3(base, base.concat({ id: 'c', n: 'C' }), [{ id: 'a', n: 'A2' }, { id: 'b', n: 'B' }]); ok('list: add here + rename there', J(m) === J([{ id: 'a', n: 'A2' }, { id: 'b', n: 'B' }, { id: 'c', n: 'C' }]), m);
m = merge3(base, [{ id: 'a', n: 'A' }], [{ id: 'a', n: 'A' }, { id: 'b', n: 'B' }, { id: 'd', n: 'D' }]); ok('list: delete here + add there', J(m) === J([{ id: 'a', n: 'A' }, { id: 'd', n: 'D' }]), m);
m = merge3(base, [{ id: 'a', n: 'A' }], [{ id: 'a', n: 'A' }, { id: 'b', n: 'B!' }]); ok('list: deleted here but edited there → keep', m.length === 2 && m[1].n === 'B!', m);
m = merge3([{ id: 'a', on: true }], [{ id: 'a', on: false }], [{ id: 'a', on: true, note: 'x' }]); ok('list item: field-level merge inside', m[0].on === false && m[0].note === 'x', m);
m = merge3(['x'], ['x', 'y'], ['x', 'z']); ok('plain list clash → this device wins (no crash)', J(m) === J(['x', 'y']), m);
m = merge3(undefined, { a: 1 }, { b: 2 }); ok('no base: object union', m.a === 1 && m.b === 2, m);
m = merge3({ a: 1 }, { a: 1 }, undefined); ok('server copy gone, nothing changed here → gone', m === undefined, m);
ok('equality ignores key order', same({ a: 1, b: { c: 2, d: 3 } }, { b: { d: 3, c: 2 }, a: 1 }) && !same({ a: 1 }, { a: 2 }) && !same(undefined, null));
m = merge3({ a: 1, _w: 'x' }, { a: 1, _w: 'x' }, { a: 2, _w: 'y' }); ok('save marker: taken from the server, never treated as data', m.a === 2 && m._w === 'y', m);
m = merge3({ c: { g: 1 }, _w: 'x' }, { c: { g: 2 }, _w: 'x' }, { c: { g: 1 }, _w: 'z' }); ok('save marker change alone is not a conflict', m.c.g === 2 && m._w === 'z', m);
const f = R.filter(x => !x.pass); console.log(`merge3: ${R.length - f.length}/${R.length} passed`); f.forEach(x => console.log('  FAIL', x.n, J(x.i)));
